import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

// Import Inter font from Google Fonts
const inter = Inter({ subsets: ['latin'] })

// Import PP Telegraf font locally
const ppTelegraf = localFont({
  src: [
    {
      path: '../../public/fonts/PPTelegraf-Regular.otf',
      // weight: '400',
    },
  ],
  variable: '--font-pp-telegraf', // CSS variable name for the font family
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ppTelegraf.variable} font-ppTelegraf bg-black`}>
        {children}
      </body>
    </html>
  )
}
