/**
 * Events / conferences — see docs/PORTFOLIO_REDESIGN.md §06.4
 */
import { pending } from './pending'
import type { EventItem } from './types'

export const events: EventItem[] = [
  {
    id: 'break-the-monolith-2025',
    type: 'hackathon',
    name: 'Break The Monolith Hackathon',
    organizer: pending('ADD organizer'),
    date: '2025',
    place: pending('ADD place'),
    role: 'Participant (Champion)',
    result: 'Champion',
    images: [],
    links: [],
    relatedProjectId: 'ride-sharing-microservices',
  },
  {
    id: 'api-avenger-cuet-2025',
    type: 'hackathon',
    name: 'API Avenger Microservice Hackathon',
    organizer: 'CUET',
    date: '2025',
    place: pending('ADD place'),
    role: 'Participant (Rising Team)',
    result: 'Rising Team',
    images: [],
    links: [],
    relatedProjectId: 'donation-backend',
  },
  {
    id: 'bs23-ai-engineering-hackathon',
    type: 'hackathon',
    name: 'AI Engineering Hackathon',
    organizer: 'Brain Station 23',
    date: pending('ADD date'),
    place: pending('ADD place'),
    role: 'Participant',
    result: pending('ADD result — optional, none stated in CV'),
    images: [],
    links: [],
    relatedProjectId: 'intent-product-search',
  },
  {
    id: 'icpc-preliminaries',
    type: 'competition',
    name: 'ICPC Preliminaries',
    date: '2022, 2023',
    place: pending('ADD place'),
    role: pending('ADD team name / role'),
    result: pending('ADD result — optional'),
    images: [],
    links: [],
  },
  {
    id: 'cuet-iupc',
    type: 'competition',
    name: 'CUET IUPC',
    date: '2022–2023',
    place: pending('ADD place'),
    role: pending('ADD team name / role'),
    result: pending('ADD result — optional'),
    images: [],
    links: [],
  },
  {
    id: 'robosoccer-cuss-2022',
    type: 'competition',
    name: 'Robosoccer Competition',
    organizer: 'Chittagong University Scientific Society (CUSS)',
    date: '2022-05', // VERIFY: CV-old says May–Jun 2022
    place: pending('ADD place'),
    role: 'Built and programmed a remote-controlled Soccer Bot (Arduino)',
    result: pending('ADD result — optional'),
    images: [],
    links: [],
    relatedProjectId: 'soccer-bot',
  },
  {
    id: 'business-competition',
    type: 'business-competition',
    name: pending('ADD business competition name'),
    organizer: pending('ADD organizer'),
    date: pending('ADD date'),
    place: pending('ADD place'),
    role: pending('ADD team / idea / your role'),
    result: pending('ADD result'),
    summary: 'Took part in a business competition.',
    images: [],
    links: [],
  },
  {
    id: 'betic-event',
    type: 'research-event',
    name: pending('ADD exact BETIC-related event name'),
    organizer: pending('ADD organizer'),
    date: pending('ADD date'),
    place: pending('ADD place'),
    role: pending('ADD your role'),
    images: [],
    links: [],
  },
]
