/**
 * Project content — see docs/PORTFOLIO_REDESIGN.md §06.4, §03.6
 */
import { pending } from './pending'
import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 'ai-studio',
    shelf: 'systems',
    name: 'AI Studio',
    oneLine: 'On-demand, multi-tenant GPU platform built on bare-metal Kubernetes and AWS.',
    problem: pending('ADD problem framing — optional, CV already covers the build'),
    role: 'Co-engineered the Kubernetes/GPU-virtualization migration and the AWS session stack',
    contribution: [
      'Migrated to bare-metal Kubernetes with HAMi GPU virtualization, cutting session launch time ~70%',
      'Architected the AWS stack: g4dn EC2, custom AMIs, ECR-hosted TensorFlow images, JuiceFS-on-S3',
      'Designed the PostgreSQL schema and REST API for GPU slice allocation and session lifecycle',
    ],
    tech: ['kubernetes', 'hami', 'aws-ec2', 'aws-s3', 'aws-ecr', 'juicefs', 'temporal', 'postgresql'],
    status: 'production',
    links: [{ kind: 'product', label: 'ai.poridhi.io', href: 'https://ai.poridhi.io' }],
    images: [],
    experienceId: 'poridhi',
  },
  {
    id: 'tensorcode',
    shelf: 'systems',
    name: 'TensorCode',
    oneLine: 'In-browser GPU IDE for live PyTorch and CUDA execution.',
    problem: pending('ADD problem framing — optional'),
    role: 'Built the edge backend; developed frontend components and architecture docs',
    contribution: [
      'Built the Hono.js backend on Cloudflare (D1, R2, KV) powering in-browser PyTorch/CUDA execution',
      'Developed React frontend components',
      'Authored the team’s architecture and deployment documentation used for onboarding',
    ],
    tech: ['hono', 'cloudflare-workers', 'cloudflare-d1', 'cloudflare-r2', 'cloudflare-kv', 'react', 'pytorch', 'cuda'],
    status: 'production',
    links: [{ kind: 'product', label: 'tensorcode.poridhi.io', href: 'https://tensorcode.poridhi.io' }],
    images: [],
    experienceId: 'poridhi',
  },
  {
    id: 'ride-sharing-microservices',
    shelf: 'hackathon',
    name: pending('ADD PROJECT NAME (event: Break The Monolith)'),
    oneLine: 'Microservices ride-sharing platform, built for Break The Monolith (2025).',
    problem: pending('ADD problem framing'),
    role: pending('ADD your specific role on the team'),
    contribution: [],
    tech: ['nodejs', 'postgresql', 'redis', 'rabbitmq'],
    status: 'prototype',
    result: 'Champion — Break The Monolith Hackathon (2025)',
    links: [], // repo/demo link pending — see docs §14
    images: [],
  },
  {
    id: 'donation-backend',
    shelf: 'hackathon',
    name: pending('ADD PROJECT NAME (event: API Avenger, CUET)'),
    oneLine: 'Donation backend with idempotent webhooks and async event handling, built for API Avenger (2025).',
    problem: pending('ADD problem framing'),
    role: pending('ADD your specific role on the team'),
    contribution: [],
    tech: [],
    status: 'prototype',
    result: 'Rising Team — API Avenger Microservice Hackathon, CUET (2025)',
    links: [],
    images: [],
  },
  {
    id: 'intent-product-search',
    shelf: 'hackathon',
    name: pending('ADD PROJECT NAME (event: Brain Station 23 AI Engineering Hackathon)'),
    oneLine: 'Intent-based product search with a quantized mini-LLM, BERT, and a full observability stack.',
    problem: pending('ADD problem framing'),
    role: pending('ADD your specific role on the team'),
    contribution: [],
    tech: [],
    status: 'prototype',
    // No placement/result stated in CV — do not invent one.
    links: [],
    images: [],
  },
  {
    id: 'soccer-bot',
    shelf: 'hardware',
    name: 'Soccer Bot',
    oneLine: 'Remote-controlled robot built for a robosoccer competition, 2022.',
    problem: pending('ADD problem framing — optional'),
    role: 'Built and programmed the bot (Arduino)',
    contribution: [],
    tech: ['arduino'],
    status: 'archived',
    date: pending('VERIFY exact dates — CV-old says May–Jun 2022'),
    links: [],
    // Photos land in /public/media/journey/workshop/ — see §13.4
    images: [
      {
        id: 'soccer-bot-photo',
        src: pending('ADD SOCCER BOT PHOTOS'),
        alt: 'The Soccer Bot built for the 2022 robosoccer competition',
        kind: 'photo',
      },
    ],
    verify: true,
  },
  {
    id: 'luca',
    shelf: 'early-web',
    name: 'Luca',
    oneLine: 'Tourist guide platform with role-based guest/host/admin dashboards.',
    problem: pending('ADD problem framing — optional'),
    role: pending('VERIFY solo vs. team project'),
    contribution: [
      'Role-based dashboards (guest/host/admin) with JWT-based authorization',
      'TanStack Query for data fetching',
      'Stripe payments',
    ],
    tech: ['react', 'nodejs', 'mongodb', 'stripe'],
    status: 'archived',
    links: [
      { kind: 'demo', label: 'Live', href: 'https://user-email-password-auth-8dfb6.web.app', verify: true },
      { kind: 'repo', label: 'GitHub', href: 'https://github.com/Anawrulkabir/Luca' },
    ],
    images: [
      {
        id: 'luca-pages',
        src: '/media/projects/luca/pages.png',
        alt: 'Luca screenshots: the homepage, tour package cards, the overview tab and a package gallery, on desktop and mobile',
        width: 1920,
        height: 1080,
        kind: 'screenshot',
      },
      {
        id: 'luca-blog-auth',
        src: '/media/projects/luca/blog-auth.png',
        alt: 'Luca screenshots: blog layouts and the login and sign-up forms',
        width: 1920,
        height: 1080,
        kind: 'screenshot',
      },
    ],
    verify: true,
  },
  {
    id: 'sitemark',
    shelf: 'early-web',
    name: 'Sitemark',
    oneLine: 'Blog platform with a Node REST API, filters, and live comments.',
    problem: pending('ADD problem framing — optional'),
    role: pending('VERIFY solo vs. team project'),
    contribution: ['Node.js REST API', 'Filters and live comments', 'Stripe payments'],
    tech: ['react', 'nodejs', 'mongodb', 'stripe'],
    status: 'archived',
    links: [
      { kind: 'demo', label: 'Live', href: 'https://aspirant-blog.web.app', verify: true },
      { kind: 'repo', label: 'Client', href: 'https://github.com/Anawrulkabir/Sitemark-client' },
      { kind: 'repo', label: 'Server', href: 'https://github.com/Anawrulkabir/Sitemark-server' },
    ],
    images: [
      {
        id: 'sitemark-home',
        src: '/media/projects/sitemark/home.png',
        alt: 'Sitemark homepage: navigation with blog sections, a sign-up hero and a sample dashboard preview',
        width: 1166,
        height: 959,
        kind: 'screenshot',
      },
    ],
    verify: true,
  },
  {
    id: 'craftpaper',
    shelf: 'early-web',
    name: 'Craftpaper',
    oneLine: 'Craft-item e-commerce site with Firebase authentication.',
    problem: pending('ADD problem framing — optional'),
    role: pending('VERIFY solo vs. team project'),
    contribution: ['Firebase Auth', 'Stripe payments'],
    tech: ['react', 'firebase', 'stripe'],
    status: 'archived',
    links: [
      { kind: 'demo', label: 'Live', href: 'https://craft-house-ad549.web.app', verify: true },
      { kind: 'repo', label: 'Client', href: 'https://github.com/Anawrulkabir/Craftpaper-client' },
      { kind: 'repo', label: 'Server', href: 'https://github.com/Anawrulkabir/Craftpaper-server' },
    ],
    images: [
      {
        id: 'craftpaper-home',
        src: '/media/projects/craftpaper/home.png',
        alt: 'Craftpaper homepage: search bar with categories, a sign-up hero with woven jute baskets, and category links',
        width: 1166,
        height: 959,
        kind: 'screenshot',
      },
    ],
    verify: true,
  },
]
